version: '3.2'
services:
  web:
    build: .
    ports:
      - 3000:3000
    volumes:
      - sftp_files:/opt/app
    depends_on:
      - db
  db:
    image: postgres
  ftp: # for development
    image: atmoz/sftp
    command: kronos:pass:2000
    depends_on:
      - web
    ports:
      - "2222:22"
    volumes:
      - sftp_files:/home/kronos/share
volumes:
  sftp_files:
    driver: local
