version: '3.2'
services:
  web:
    build: .
    ports:
      - 3000:3000
    volumes:
      - samba_share:/opt/app
    depends_on:
      - db
  db:
    image: postgres
  samba: # for development
    image: dperson/samba
    ports:
      - "139:139"
      - "445:445"
    environment:
      - "USERID=0"
      - "GROUPID=0"
    command: "-s 'share;/share;;no'"
    depends_on:
      - web
    volumes:
      - samba_share:/share
volumes:
  samba_share:
    driver: local
