version: '3.2'
services:
  web:
    build: .
    user: root
    ports:
      - 3000:3000
    volumes:
      - sftp_files:/opt/app
    depends_on:
      - db
  db:
    image: postgres
  ftp:
    image: atmoz/sftp
    command: kronos:pass
    depends_on:
      - web
    ports:
      - "2222:22"
    volumes:
      - sftp_files:/opt/app
volumes:
  sftp_files:
    driver: local
