version: '3.2'
services:
  web:
    build: .
    ports:
      - 3000:3000
    volumes:
      - type: volume
        source: mydata
        target: /opt/app
        volume:
          nocopy: false
    depends_on:
      - db
  db:
    image: postgres
  ftp:
    image: atmoz/sftp
    command: foo:bar
    ports:
      - "2222:22"
    volumes:
      - type: volume
        source: mydata
        target: /home/foo/share
volumes:
  mydata:
#  - /opt/volumes/mydata:/opt/app
